insert into fee_rule (id, name, rate, sql_restrictions, is_default)
values (-1, '', 10, '', '1');

insert into country (name, iso2, iso3, code)values ('Afghanistan','AF','AFG',4);
insert into country (name, iso2, iso3, code)values ('Afrique du Sud','ZA','ZAF',710);
insert into country (name, iso2, iso3, code)values ('Albanie','AL','ALB',8);
insert into country (name, iso2, iso3, code)values ('Algerie','DZ','DZA',12);
insert into country (name, iso2, iso3, code)values ('Allemagne','DE','DEU',276);
insert into country (name, iso2, iso3, code)values ('Andorre','AD','AND',20);
insert into country (name, iso2, iso3, code)values ('Angola','AO','AGO',24);
insert into country (name, iso2, iso3, code)values ('Anguilla','AI','AIA',660);
insert into country (name, iso2, iso3, code)values ('Antarctique','AQ','ATA',10);
insert into country (name, iso2, iso3, code)values ('Antigua et Barbuda','AG','ATG',28);
insert into country (name, iso2, iso3, code)values ('Antilles Néerlandaises','AN','ANT',530);
insert into country (name, iso2, iso3, code)values ('Arabie Saoudite','SA','SAU',682);
insert into country (name, iso2, iso3, code)values ('Argentine','AR','ARG',32);
insert into country (name, iso2, iso3, code)values ('Arménie','AM','ARM',51);
insert into country (name, iso2, iso3, code)values ('Aruba','AW','ABW',533);
insert into country (name, iso2, iso3, code)values ('Australie','AU','AUS',36);
insert into country (name, iso2, iso3, code)values ('Autriche','AT','AUT',40);
insert into country (name, iso2, iso3, code)values ('Azerbaidjan','AZ','AZE',31);
insert into country (name, iso2, iso3, code)values ('Bahamas','BS','BHS',44);
insert into country (name, iso2, iso3, code)values ('Bahrein','BH','BHR',48);
insert into country (name, iso2, iso3, code)values ('Bangladesh','BD','BGD',50);
insert into country (name, iso2, iso3, code)values ('Barbade','BB','BRB',52);
insert into country (name, iso2, iso3, code)values ('Bélarus (Biélorussie)','BY','BLR',112);
insert into country (name, iso2, iso3, code)values ('Belgique','BE','BEL',56);
insert into country (name, iso2, iso3, code)values ('Belize','BZ','BLZ',84);
insert into country (name, iso2, iso3, code)values ('Bénin','BJ','BEN',204);
insert into country (name, iso2, iso3, code)values ('Bermudes','BM','BMU',60);
insert into country (name, iso2, iso3, code)values ('Bhoutan','BT','BTN',64);
insert into country (name, iso2, iso3, code)values ('Bolivie','BO','BOL',68);
insert into country (name, iso2, iso3, code)values ('Bosnie et Herzégovine','BA','BIH',70);
insert into country (name, iso2, iso3, code)values ('Botswana','BW','BWA',72);
insert into country (name, iso2, iso3, code)values ('Bouvet Island','BV','BVT',74);
insert into country (name, iso2, iso3, code)values ('Brésil','BR','BRA',76);
insert into country (name, iso2, iso3, code)values ('Brunei','BN','BRN',96);
insert into country (name, iso2, iso3, code)values ('Bulgarie','BG','BGR',100);
insert into country (name, iso2, iso3, code)values ('Burkina Faso','BF','BFA',854);
insert into country (name, iso2, iso3, code)values ('Burundi','BI','BDI',108);
insert into country (name, iso2, iso3, code)values ('Cambodge','KH','KHM',116);
insert into country (name, iso2, iso3, code)values ('Cameroun','CM','CMR',120);
insert into country (name, iso2, iso3, code)values ('Canada','CA','CAN',124);
insert into country (name, iso2, iso3, code)values ('Cap Vert','CV','CPV',132);
insert into country (name, iso2, iso3, code)values ('Chili','CL','CHL',152);
insert into country (name, iso2, iso3, code)values ('Chine','CN','CHN',156);
insert into country (name, iso2, iso3, code)values ('Chypre','CY','CYP',196);
insert into country (name, iso2, iso3, code)values ('Cité du Vatican (Holy See)','VA','VAT',336);
insert into country (name, iso2, iso3, code)values ('Colombie','CO','COL',170);
insert into country (name, iso2, iso3, code)values ('Comores','KM','COM',174);
insert into country (name, iso2, iso3, code)values ('Congo, République','CG','COG',178);
insert into country (name, iso2, iso3, code)values ('Congo, République Démocratique du','CD','COD',180);
insert into country (name, iso2, iso3, code)values ('Corée du Nord','KP','PRK',408);
insert into country (name, iso2, iso3, code)values ('Corée du Sud','KR','KOR',410);
insert into country (name, iso2, iso3, code)values ('Costa Rica','CR','CRI',188);
insert into country (name, iso2, iso3, code)values ('Côte d''Ivoire','CI','CIV',384);
insert into country (name, iso2, iso3, code)values ('Croatie','HR','HRV',191);
insert into country (name, iso2, iso3, code)values ('Cuba','CU','CUB',192);
insert into country (name, iso2, iso3, code)values ('Curacao','CW','CUW',531);
insert into country (name, iso2, iso3, code)values ('Danemark','DK','DNK',208);
insert into country (name, iso2, iso3, code)values ('Djibouti','DJ','DJI',262);
insert into country (name, iso2, iso3, code)values ('Dominique','DM','DMA',212);
insert into country (name, iso2, iso3, code)values ('Egypte','EG','EGY',818);
insert into country (name, iso2, iso3, code)values ('Emirats Arabes Unis','AE','ARE',784);
insert into country (name, iso2, iso3, code)values ('Equateur','EC','ECU',218);
insert into country (name, iso2, iso3, code)values ('Erythrée','ER','ERI',232);
insert into country (name, iso2, iso3, code)values ('Espagne','ES','ESP',724);
insert into country (name, iso2, iso3, code)values ('Estonie','EE','EST',233);
insert into country (name, iso2, iso3, code)values ('Etats-Unis','US','USA',840);
insert into country (name, iso2, iso3, code)values ('Ethiopie','ET','ETH',231);
insert into country (name, iso2, iso3, code)values ('Fidji','FJ','FJI',242);
insert into country (name, iso2, iso3, code)values ('Finlande','FI','FIN',246);
insert into country (name, iso2, iso3, code)values ('France','FR','FRA',250);
insert into country (name, iso2, iso3, code)values ('France, Métropolitaine','FX','FXX',249);
insert into country (name, iso2, iso3, code)values ('Gabon','GA','GAB',266);
insert into country (name, iso2, iso3, code)values ('Gambie','GM','GMB',270);
insert into country (name, iso2, iso3, code)values ('Gaza','PS','PSE',275);
insert into country (name, iso2, iso3, code)values ('Géorgie','GE','GEO',268);
insert into country (name, iso2, iso3, code)values ('Géorgie du Sud et les îles Sandwich du Sud','GS','SGS',239);
insert into country (name, iso2, iso3, code)values ('Ghana','GH','GHA',288);
insert into country (name, iso2, iso3, code)values ('Gibraltar','GI','GIB',292);
insert into country (name, iso2, iso3, code)values ('Grèce','GR','GRC',300);
insert into country (name, iso2, iso3, code)values ('Grenade','GD','GRD',308);
insert into country (name, iso2, iso3, code)values ('Greoenland','GL','GRL',304);
insert into country (name, iso2, iso3, code)values ('Guadeloupe','GP','GLP',312);
insert into country (name, iso2, iso3, code)values ('Guam','GU','GUM',316);
insert into country (name, iso2, iso3, code)values ('Guatemala','GT','GTM',320);
insert into country (name, iso2, iso3, code)values ('Guinée','GN','GIN',324);
insert into country (name, iso2, iso3, code)values ('Guinée Bissau','GW','GNB',624);
insert into country (name, iso2, iso3, code)values ('Guinée Equatoriale','GQ','GNQ',226);
insert into country (name, iso2, iso3, code)values ('Guyane','GY','GUY',328);
insert into country (name, iso2, iso3, code)values ('Guyane Française','GF','GUF',254);
insert into country (name, iso2, iso3, code)values ('Haïti','HT','HTI',332);
insert into country (name, iso2, iso3, code)values ('Honduras','HN','HND',340);
insert into country (name, iso2, iso3, code)values ('Hong Kong','HK','HKG',344);
insert into country (name, iso2, iso3, code)values ('Hongrie','HU','HUN',348);
insert into country (name, iso2, iso3, code)values ('Ile de Man','IM','IMN',833);
insert into country (name, iso2, iso3, code)values ('Iles Caïman','KY','CYM',136);
insert into country (name, iso2, iso3, code)values ('Iles Christmas','CX','CXR',162);
insert into country (name, iso2, iso3, code)values ('Iles Cocos','CC','CCK',166);
insert into country (name, iso2, iso3, code)values ('Iles Cook','CK','COK',184);
insert into country (name, iso2, iso3, code)values ('Iles Féroé','FO','FRO',234);
insert into country (name, iso2, iso3, code)values ('Iles Guernesey','GG','GGY',831);
insert into country (name, iso2, iso3, code)values ('Iles Heardet McDonald','HM','HMD',334);
insert into country (name, iso2, iso3, code)values ('Iles Malouines','FK','FLK',238);
insert into country (name, iso2, iso3, code)values ('Iles Mariannes du Nord','MP','MNP',580);
insert into country (name, iso2, iso3, code)values ('Iles Marshall','MH','MHL',584);
insert into country (name, iso2, iso3, code)values ('Iles Maurice','MU','MUS',480);
insert into country (name, iso2, iso3, code)values ('Iles mineures éloignées des Etats-Unis','UM','UMI',581);
insert into country (name, iso2, iso3, code)values ('Iles Norfolk','NF','NFK',574);
insert into country (name, iso2, iso3, code)values ('Iles Salomon','SB','SLB',90);
insert into country (name, iso2, iso3, code)values ('Iles Turques et Caïque','TC','TCA',796);
insert into country (name, iso2, iso3, code)values ('Iles Vierges des Etats-Unis','VI','VIR',850);
insert into country (name, iso2, iso3, code)values ('Iles Vierges du Royaume-Uni','VG','VGB',92);
insert into country (name, iso2, iso3, code)values ('Inde','IN','IND',356);
insert into country (name, iso2, iso3, code)values ('Indonésie','ID','IDN',360);
insert into country (name, iso2, iso3, code)values ('Iraq','IQ','IRQ',368);
insert into country (name, iso2, iso3, code)values ('Iran','IR','IRN',364);
insert into country (name, iso2, iso3, code)values ('Irlande','IE','IRL',372);
insert into country (name, iso2, iso3, code)values ('Islande','IS','ISL',352);
insert into country (name, iso2, iso3, code)values ('Israël','IL','ISR',376);
insert into country (name, iso2, iso3, code)values ('Italie','IT','ITA',380);
insert into country (name, iso2, iso3, code)values ('Jamaique','JM','JAM',388);
insert into country (name, iso2, iso3, code)values ('Japon','JP','JPN',392);
insert into country (name, iso2, iso3, code)values ('Jersey','JE','JEY',832);
insert into country (name, iso2, iso3, code)values ('Jordanie','JO','JOR',400);
insert into country (name, iso2, iso3, code)values ('Kazakhstan','KZ','KAZ',398);
insert into country (name, iso2, iso3, code)values ('Kenya','KE','KEN',404);
insert into country (name, iso2, iso3, code)values ('Kirghizistan','KG','KGZ',417);
insert into country (name, iso2, iso3, code)values ('Kiribati','KI','KIR',296);
insert into country (name, iso2, iso3, code)values ('Koweit','KW','KWT',414);
insert into country (name, iso2, iso3, code)values ('Laos','LA','LAO',418);
insert into country (name, iso2, iso3, code)values ('Lesotho','LS','LSO',426);
insert into country (name, iso2, iso3, code)values ('Lettonie','LV','LVA',428);
insert into country (name, iso2, iso3, code)values ('Liban','LB','LBN',422);
insert into country (name, iso2, iso3, code)values ('Libéria','LR','LBR',430);
insert into country (name, iso2, iso3, code)values ('Libye','LY','LBY',434);
insert into country (name, iso2, iso3, code)values ('Liechtenstein','LI','LIE',438);
insert into country (name, iso2, iso3, code)values ('Lituanie','LT','LTU',440);
insert into country (name, iso2, iso3, code)values ('Luxembourg','LU','LUX',442);
insert into country (name, iso2, iso3, code)values ('Macao','MO','MAC',446);
insert into country (name, iso2, iso3, code)values ('Macédoine','MK','MKD',807);
insert into country (name, iso2, iso3, code)values ('Madagascar','MG','MDG',450);
insert into country (name, iso2, iso3, code)values ('Malaisie','MY','MYS',458);
insert into country (name, iso2, iso3, code)values ('Malawi','MW','MWI',454);
insert into country (name, iso2, iso3, code)values ('Maldives','MV','MDV',462);
insert into country (name, iso2, iso3, code)values ('Mali','ML','MLI',466);
insert into country (name, iso2, iso3, code)values ('Malte','MT','MLT',470);
insert into country (name, iso2, iso3, code)values ('Maroc','MA','MAR',504);
insert into country (name, iso2, iso3, code)values ('Martinique','MQ','MTQ',474);
insert into country (name, iso2, iso3, code)values ('Mauritanie','MR','MRT',478);
insert into country (name, iso2, iso3, code)values ('Mayotte','YT','MYT',175);
insert into country (name, iso2, iso3, code)values ('Mexique','MX','MEX',484);
insert into country (name, iso2, iso3, code)values ('Micronésie','FM','FSM',583);
insert into country (name, iso2, iso3, code)values ('Moldavie','MD','MDA',498);
insert into country (name, iso2, iso3, code)values ('Monaco','MC','MCO',492);
insert into country (name, iso2, iso3, code)values ('Mongolie','MN','MNG',496);
insert into country (name, iso2, iso3, code)values ('Monténégro','ME','MNE',499);
insert into country (name, iso2, iso3, code)values ('Montserrat','MS','MSR',500);
insert into country (name, iso2, iso3, code)values ('Mozambique','MZ','MOZ',508);
insert into country (name, iso2, iso3, code)values ('Myanmar (Birmanie)','MM','MMR',104);
insert into country (name, iso2, iso3, code)values ('Namibie','NA','NAM',516);
insert into country (name, iso2, iso3, code)values ('Nauru','NR','NRU',520);
insert into country (name, iso2, iso3, code)values ('Népal','NP','NPL',524);
insert into country (name, iso2, iso3, code)values ('Nicaragua','NI','NIC',558);
insert into country (name, iso2, iso3, code)values ('Niger','NE','NER',562);
insert into country (name, iso2, iso3, code)values ('Nigeria','NG','NGA',566);
insert into country (name, iso2, iso3, code)values ('Niue','NU','NIU',570);
insert into country (name, iso2, iso3, code)values ('Norvège','NO','NOR',578);
insert into country (name, iso2, iso3, code)values ('Nouvelle Calédonie','NC','NCL',540);
insert into country (name, iso2, iso3, code)values ('Nouvelle Zélande','NZ','NZL',554);
insert into country (name, iso2, iso3, code)values ('Oman','OM','OMN',512);
insert into country (name, iso2, iso3, code)values ('Ouganda','UG','UGA',800);
insert into country (name, iso2, iso3, code)values ('Ouzbékistan','UZ','UZB',860);
insert into country (name, iso2, iso3, code)values ('Pakistan','PK','PAK',586);
insert into country (name, iso2, iso3, code)values ('Palau','PW','PLW',585);
insert into country (name, iso2, iso3, code)values ('Panama','PA','PAN',591);
insert into country (name, iso2, iso3, code)values ('Papouasie Nouvelle Guinée','PG','PNG',598);
insert into country (name, iso2, iso3, code)values ('Paraguay','PY','PRY',600);
insert into country (name, iso2, iso3, code)values ('Pays-Bas','NL','NLD',528);
insert into country (name, iso2, iso3, code)values ('Pérou','PE','PER',604);
insert into country (name, iso2, iso3, code)values ('Philippines','PH','PHL',608);
insert into country (name, iso2, iso3, code)values ('Pitcairn','PN','PCN',612);
insert into country (name, iso2, iso3, code)values ('Pologne','PL','POL',616);
insert into country (name, iso2, iso3, code)values ('Polynésie Française','PF','PYF',258);
insert into country (name, iso2, iso3, code)values ('Porto Rico','PR','PRI',630);
insert into country (name, iso2, iso3, code)values ('Portugal','PT','PRT',620);
insert into country (name, iso2, iso3, code)values ('Qatar','QA','QAT',634);
insert into country (name, iso2, iso3, code)values ('République Centraficaine','CF','CAF',140);
insert into country (name, iso2, iso3, code)values ('République Dominicaine','DO','DOM',214);
insert into country (name, iso2, iso3, code)values ('République Tchèque','CZ','CZE',203);
insert into country (name, iso2, iso3, code)values ('Réunion','RE','REU',638);
insert into country (name, iso2, iso3, code)values ('Roumanie','RO','ROU',642);
insert into country (name, iso2, iso3, code)values ('Royaume Uni','GB','GBR',826);
insert into country (name, iso2, iso3, code)values ('Russie','RU','RUS',643);
insert into country (name, iso2, iso3, code)values ('Rwanda','RW','RWA',646);
insert into country (name, iso2, iso3, code)values ('Sahara Occidental','EH','ESH',732);
insert into country (name, iso2, iso3, code)values ('Saint Barthelemy','BL','BLM',652);
insert into country (name, iso2, iso3, code)values ('Saint Hélène','SH','SHN',654);
insert into country (name, iso2, iso3, code)values ('Saint Kitts et Nevis','KN','KNA',659);
insert into country (name, iso2, iso3, code)values ('Saint Martin','MF','MAF',663);
insert into country (name, iso2, iso3, code)values ('Saint Martin','SX','SXM',534);
insert into country (name, iso2, iso3, code)values ('Saint Pierre et Miquelon','PM','SPM',666);
insert into country (name, iso2, iso3, code)values ('Saint Vincent et les Grenadines','VC','VCT',670);
insert into country (name, iso2, iso3, code)values ('Sainte Lucie','LC','LCA',662);
insert into country (name, iso2, iso3, code)values ('Salvador','SV','SLV',222);
insert into country (name, iso2, iso3, code)values ('Samoa Americaines','AS','ASM',16);
insert into country (name, iso2, iso3, code)values ('Samoa Occidentales','WS','WSM',882);
insert into country (name, iso2, iso3, code)values ('San Marin','SM','SMR',674);
insert into country (name, iso2, iso3, code)values ('Sao Tomé et Principe','ST','STP',678);
insert into country (name, iso2, iso3, code)values ('Sénégal','SN','SEN',686);
insert into country (name, iso2, iso3, code)values ('Serbie','RS','SRB',688);
insert into country (name, iso2, iso3, code)values ('Seychelles','SC','SYC',690);
insert into country (name, iso2, iso3, code)values ('Sierra Léone','SL','SLE',694);
insert into country (name, iso2, iso3, code)values ('Singapour','SG','SGP',702);
insert into country (name, iso2, iso3, code)values ('Slovaquie','SK','SVK',703);
insert into country (name, iso2, iso3, code)values ('Slovénie','SI','SVN',705);
insert into country (name, iso2, iso3, code)values ('Somalie','SO','SOM',706);
insert into country (name, iso2, iso3, code)values ('Soudan','SD','SDN',729);
insert into country (name, iso2, iso3, code)values ('Sri Lanka','LK','LKA',144);
insert into country (name, iso2, iso3, code)values ('Sud Soudan','SS','SSD',728);
insert into country (name, iso2, iso3, code)values ('Suède','SE','SWE',752);
insert into country (name, iso2, iso3, code)values ('Suisse','CH','CHE',756);
insert into country (name, iso2, iso3, code)values ('Surinam','SR','SUR',740);
insert into country (name, iso2, iso3, code)values ('Svalbard et Jan Mayen','SJ','SJM',744);
insert into country (name, iso2, iso3, code)values ('Swaziland','SZ','SWZ',748);
insert into country (name, iso2, iso3, code)values ('Syrie','SY','SYR',760);
insert into country (name, iso2, iso3, code)values ('Tadjikistan','TJ','TJK',762);
insert into country (name, iso2, iso3, code)values ('Taiwan','TW','TWN',158);
insert into country (name, iso2, iso3, code)values ('Tanzanie','TZ','TZA',834);
insert into country (name, iso2, iso3, code)values ('Tchad','TD','TCD',148);
insert into country (name, iso2, iso3, code)values ('Terres Australes et Antarctique Françaises','TF','ATF',260);
insert into country (name, iso2, iso3, code)values ('Térritoire Britannique de l''Océan Indien','IO','IOT',86);
insert into country (name, iso2, iso3, code)values ('Thaïlande','TH','THA',764);
insert into country (name, iso2, iso3, code)values ('Timor-Leste','TL','TLS',626);
insert into country (name, iso2, iso3, code)values ('Togo','TG','TGO',768);
insert into country (name, iso2, iso3, code)values ('Tokelau','TK','TKL',772);
insert into country (name, iso2, iso3, code)values ('Tonga','TO','TON',776);
insert into country (name, iso2, iso3, code)values ('Trinité et Tobago','TT','TTO',780);
insert into country (name, iso2, iso3, code)values ('Tunisie','TN','TUN',788);
insert into country (name, iso2, iso3, code)values ('Turkmenistan','TM','TKM',795);
insert into country (name, iso2, iso3, code)values ('Turquie','TR','TUR',792);
insert into country (name, iso2, iso3, code)values ('Tuvalu','TV','TUV',798);
insert into country (name, iso2, iso3, code)values ('Ukraine','UA','UKR',804);
insert into country (name, iso2, iso3, code)values ('Uruguay','UY','URY',858);
insert into country (name, iso2, iso3, code)values ('Vanuatu','VU','VUT',548);
insert into country (name, iso2, iso3, code)values ('Venezuela','VE','VEN',862);
insert into country (name, iso2, iso3, code)values ('Vietnam','VN','VNM',704);
insert into country (name, iso2, iso3, code)values ('Wallis et Futuna','WF','WLF',876);
insert into country (name, iso2, iso3, code)values ('Yemen','YE','YEM',887);
insert into country (name, iso2, iso3, code)values ('Zambie','ZM','ZMB',894);
insert into country (name, iso2, iso3, code)values ('Zimbabwe','ZW','ZWE',716);