swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Orge Api Webservice"
paths:
  /rule:
    post:
      operationId: "addRule"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: Authorization
          in: header
          description: bearer authorisation.
          required: true
          type: string
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Rule"
      responses:
        200:
          description: "successful operation"
  /fee:
    post:
      operationId: "computeFee"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: Authorization
          in: header
          description: bearer authorisation.
          required: true
          type: string
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/FeeRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Fee"
definitions:
  Fee:
    type: "object"
    properties:
      fees:
        type: "integer"
        format: "int32"
      reason:
        type: "string"
  FeeRequest:
    type: "object"
    properties:
      client:
        $ref: "#/definitions/Ip"
      freelancer:
        $ref: "#/definitions/Ip"
      mission:
        $ref: "#/definitions/MissionDuration"
      commercialrelation:
        $ref: "#/definitions/CommercialRelation"
  CommercialRelation:
    type: "object"
    properties:
        firstmission :
          type: string
          format: date-time
        last_mission :
          type: string
          format: date-time
  MissionDuration:
    type: "object"
    properties:
      length:
        type : "string"
  Ip:
    type: "object"
    properties:
      ip:
        type : "string"
  Rule:
    type: "object"
    properties:
      name:
        type: "string"
      rate :
        $ref: "#/definitions/Rate"
      restrictions:
        type: "object"
  Rate:
    type: "object"
    properties:
      percent :
        type: "integer"
        format: "int32"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"